apiVersion: apps/v1
kind: Deployment
metadata:
  name: samples
  labels:
    app: samples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples
  template:
    metadata:
      labels:
        app: samples
    spec:
      containers:
        - name: samples
          image: 908198849120.dkr.ecr.ap-south-1.amazonaws.com/devopshint:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

            